---
plan: free
capacity: 200
local_db: sqlite3:/var/vcap/services/activemq/activemq_node.db
mbus: nats://localhost:4222
base_dir: /var/vcap/services/activemq/instances
index: 0
logging:
  level: debug
ip_route: 127.0.0.1
max_memory: 16
pid: /var/vcap/sys/run/activemq_node.pid
node_id: activemq_node_free_1
migration_nfs: /mnt/appcloud
max_clients: 1000
port_range:
  first: 61001
  last: 62000
admin_port_range:
  first: 8001
  last: 9000
activemq_server: /opt/activemq/apache-activemq-5.6.0/
activemq_log_dir: /var/vcap/sys/log/activemq
activemq_start_timeout: 20
# z_interval: 30
# max_nats_payload: 1048576
# fqdn_hosts: false
